# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-03-01 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='vacancy',
            table='vacancy',
        ),
        migrations.AlterModelTable(
            name='worker',
            table='worker',
        ),
    ]
