# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-03-01 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0002_auto_20230301_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_category',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='category_vanacy',
            new_name='category_vacancy',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='name',
            new_name='name_vacancy',
        ),
    ]
