# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-03-02 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0003_auto_20230302_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='job',
            new_name='vacancy',
        ),
    ]
