# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-03-02 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0004_auto_20230302_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(default='муж', max_length=8),
            preserve_default=False,
        ),
    ]
