# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-03-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0006_auto_20230302_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('gender', models.CharField(default='муж', max_length=8)),
                ('date_birth', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='worker',
            name='human',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='work_app.Human'),
            preserve_default=False,
        ),
    ]
