# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-03-09 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0007_auto_20230309_1810'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='human',
            table='human',
        ),
    ]
